### ISSUE TITLE
[FEAT]: Create Dev Branch

### ISSUE THREAD

**Issue by noboaki** [Animealth/animealth-backend#2]
## 🔨: 상세 작업 내용
- [x] 1. 깃 브랜치 전략을 위한 Dev 브랜치 생성

## 📃: 참고 사항
- 기능 개발의 경우 Dev 브랜치 상에서 이루어지며, 일정에 따라 Dev 브랜치와 main 브랜치를 병합한다

## ⏳: 예상 소요 기간
 - 시작일: 2024.06.05 
 - 마감일: 2024.06.09

**Comment by yeomyaloo** [comment]
뭐요 이건
