### ISSUE TITLE
[FEAT]: User Base Entity

### ISSUE THREAD

**Issue by MJLee39** [Animealth/animealth-backend#7]
## 🔨: 상세 작업 내용
- [ ] Create User Entity
- [ ] User base entity 생성

## 📃: 참고 사항
- 엔티티 클래스를 정의하고 데이터베이스 스키마를 설정하는 작업을 합니다.

## ⏳: 예상 소요 기간
 - 1일

**Comment by yeomyaloo** [comment]
오 뭐냐구 ! 했냐구 명진짱~~!@!

**Comment by MJLee39** [comment]
base entity 생성했습니다.
